import React, { useMemo } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Chat from '../components/Chat'
import Test from '../components/Test'
import MainLayout from 'components/layout/MainLayout'
import QR from 'components/QR'
import { uuid4 } from 'lib/utils'

export default function Home() {
  const gameId = useMemo(() => uuid4(), [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h1>Let&apos;s play Game!</h1>

        <p>
          Find the diffrent <code>QR code!</code>
        </p>

        <div>
          <QR
            url={'remote'}
            query={{ 'game-id': gameId }}
            data-tip="start"
            onDevelopment={true}
          />
        </div>
      </MainLayout>
    </div>
  )
}
